### ISSUE TITLE
LIST parameters don't work

### ISSUE THREAD

**Issue by dusupark** [ashkulz/NppFTP#160] opened 2017-05-24 00:54 UTC
### Description of the Issue

I've downloaded and installed NppFTP-x64.zip. I have troubled with find a file because the directories and files are not listed in alphabetical order. Then, I try to set the LIST parameters in the FTP Misc tab, Profile settings, but it doesn't work.

### Steps to Reproduce the Issue

1.  Connect to any FTP server.
2. 
3. 

### Expected Behavior

The directories and files are listed in alphabetical order:
data
img
js
product
webservice

### Actual Behavior

The directories and files are not listed in alphabetical order:
img
product
webservice
data
js

**Comment by chcg** [comment] 2017-05-24 21:39
Probably an issue of the list retrieved from the server. Didn't oberved this e.g. with 'ftp.heise.de'.

**Comment by NewbLuck** [comment] 2017-07-21 20:07
Confirming the issue.  Updated to x86 0.27.0 and had the sorting issue, rolled back to x86 0.26.9 and the issue went away.  Guessing it was the change in FileObject::CompareFO return cast and how it interacts with the isDir?false:true line in the same method, can't currently build to verify.

**Comment by bethannon** [comment] 2017-07-27 22:10
Also confirming this issue. Currently running 0.27.0.

Seeing:
wp-admin
cgi-bin
wp-includes
.well-known
wp-content

**Comment by JaroslavHerber** [comment] 2017-08-01 09:07
Confirmed!
Sorting is not alphanumeric!
Please fix

**Comment by alexwai** [comment] 2017-08-09 06:57
Confirmed as well.. Does not sort file accordingly. need a fix..

**Comment by Tom0129** [comment] 2017-08-11 07:58
Confirmed here, it's quite annoying.
Rolling back to a previous ver. resolve the problem but add some more.
Please, check it out.
Thanks !

**Comment by levinla** [comment] 2017-08-12 10:44
The same thing. Please fix!
What is the best stable version? Can anybody recommend please?

**Comment by vlakant** [comment] 2017-08-12 16:57
I have the same problem. :(

**Comment by maracom** [comment] 2017-08-14 02:55
Same problem here.

**Comment by JaroslavHerber** [comment] 2017-08-18 09:53
Can someone provide a patch? Maybe a pull request? @ashkulz

**Comment by m-overlund** [comment] 2017-08-18 17:24
Same issue here - on both x86 and x64 versions

**Comment by chcg** [comment] 2017-08-18 20:31
Could reproduce the issue with 32 and 64 bit version. Initial guess from @NewbLuck that https://github.com/ashkulz/NppFTP/commit/48cf35dbb8b5b221817f0593986d0cdc9c9a3c25 caused it seems reasonable. Probably the 
- correct invalid comparator issue due to not strictly weak ordering impl issue
part.
I need to check this further and how to repair it.

**Comment by chcg** [comment] 2017-08-22 20:29
Example: anonymous ftp://ftp.uni-erlangen.de/ctan/

**Comment by chcg** [comment] 2017-08-27 05:40
Example of problematic ftp dir: anonymous ftp://ftp.uni-erlangen.de/ctan/documentation

**Comment by chcg** [comment] 2017-08-27 08:35
Considered to be fixed with https://github.com/ashkulz/NppFTP/releases/tag/v0.27.1

**Closed** 2017-08-27 08:35 UTC
Labels: bug

**Comment by bethannon** [comment] 2017-08-29 02:53
Confirming that https://github.com/ashkulz/NppFTP/releases/tag/v0.27.1 fixes the non-alpha order issue. Thanks!
