### ISSUE TITLE
NppFTP crashes when private key path is invalid

### ISSUE THREAD

**Issue by henshin** [ashkulz/NppFTP#49] opened 2015-07-21 13:27 UTC
Hi,

I noticed that NppFTP doesn't check if the private key path is valid before attempting to connect. That probably triggers an internal file not found error and that causes Notepad++ to crash.

It should be easy to reproduce. Setup a new connection which allows just private key file authentication, set a wrong path for the private key, save and then try to connect to that host.

**Comment by therealjeremycole** [comment] 2015-10-26 22:26
Thanks for posting this - was driving me nuts.  It should also check to make sure one is selecting an openssh style key (and not a .ppk file for example) which will also cause a crash.

**Comment by martin-rueegg** [comment] 2016-09-28 08:33
Same here. In my case, the path is valid, but the network drive has become marked "unavailable". once the drive is accessed in Windows Explorer, it's marked "available" again, and NppFTP succeeds.

**Comment by martin-rueegg** [comment] 2016-09-28 08:34
actually a duplicate of #32

**Comment by chcg** [comment] 2017-05-22 21:41
@therealjeremycole @henshin @martin-rueegg  dup to #32 and #91 , fix released with https://github.com/ashkulz/NppFTP/releases/tag/v0.27.0, please check

**Comment by chcg** [comment] 2017-05-22 21:44
@therealjeremycole the openssh style key is a dup to #22 and will be tracked there

**Closed** 2017-05-31 21:58 UTC
Labels: bug, duplicate
